"""empty message

Revision ID: a333e291a0a6
Revises: 873745ae0947
Create Date: 2024-09-02 16:21:06.993047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a333e291a0a6'
down_revision = '873745ae0947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_vehicle')
    op.drop_table('favorite_character')
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planet_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_planet_pkey')
    )
    op.create_table('favorite_character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_character_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_character_pkey')
    )
    op.create_table('favorite_vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_vehicle_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_vehicle_pkey')
    )
    # ### end Alembic commands ###
